/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: gaelinix (https://sketchfab.com/gaelinix)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cloud-high-poly-7f3c3f525f8e42d3b99dcfe3abbc5e54
Title: CLOUD high poly
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import cloudScene from "../assets/models/3D/cloud.glb";
import { fadeOnBeforeCompile } from "../utils/fadeMaterial";

export function Cloud({ opacity, ...props }) {
  const { nodes, materials } = useGLTF(cloudScene);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Nube001_Material_0.geometry}
        material={materials.Material}
      >
        <meshStandardMaterial
          onBeforeCompile={fadeOnBeforeCompile}
          envMapIntensity={2}
          transparent
          opacity={opacity}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload(cloudScene);
