/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src/assets/models/3D/plane.glb 
Author: Ab.316 (https://sketchfab.com/Ab.316)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/plane-3684a5895e8f4b84ab7e5263a3aa9bf6
Title: Plane
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import planeScene from "../assets/models/3D/plane.glb";

export function Plane(props) {
  const { nodes, materials } = useGLTF(planeScene);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials["Material.001"]}
        rotation={[0, 0.406, 0]}
        scale={[1, 0.165, 1]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials["Material.001"]}
        position={[0.035, 0, 0.993]}
        scale={[0.345, 0.036, 0.345]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials["Material.001"]}
        position={[0.035, 0, -0.988]}
        rotation={[-Math.PI, 0, 0]}
        scale={[0.345, 0.036, 0.345]}
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials["Material.001"]}
        position={[0, 0.007, 0.837]}
        scale={[0.534, 0.088, 0.065]}
      />
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials["Material.001"]}
        position={[0, 0.007, -0.839]}
        scale={[0.534, 0.088, 0.065]}
      />
      <mesh
        geometry={nodes.Object_14.geometry}
        material={materials["Material.001"]}
        position={[-1.345, 0.735, -0.548]}
        rotation={[0, 0, 0.056]}
        scale={[0.317, 0.048, 0.318]}
      />
      <mesh
        geometry={nodes.Object_16.geometry}
        material={materials["Material.001"]}
        position={[0.133, -0.123, -0.027]}
        rotation={[0, 0, 0.014]}
        scale={[1.355, 0.244, 0.244]}
      />
    </group>
  );
}

useGLTF.preload(planeScene);
